### ISSUE TITLE
where can I find the 'vitpose-h-multi-coco.pth'?

### ISSUE THREAD

**Issue by HenrySomeCode** [kasvii/PMCE#2]
Hi, I do not see any file named 'vitpose-h-multi-coco.pth' in this link: https://onedrive.live.com/?authkey=%21AJmKbZYKgXlKdss&id=D70F26D613E83858%21318&cid=D70F26D613E83858

**Comment by kasvii** [comment]
Thanks for pointing out this. `vitpose-h-multi-coco.pth` has been uploaded to the [link](https://onedrive.live.com/?authkey=%21AJmKbZYKgXlKdss&id=D70F26D613E83858%21318&cid=D70F26D613E83858).
