### ISSUE TITLE
where can I find the 'smpl_mean_vertices.npy'? 

### ISSUE THREAD

**Issue by HenrySomeCode** [kasvii/PMCE#3]
When I ran the inference command on colab (I rebuilt this repo on colab):

```
!python ./main/run_demo.py --vid_file demo/sample_video.mp4 --gpu 0
```
I get this error:

```
Traceback (most recent call last):
  File "/content/PMCE/./main/run_demo.py", line 495, in <module>
    main(args)
  File "/content/PMCE/./main/run_demo.py", line 239, in main
    model, joint_regressor, joint_num, skeleton, ckt_name = get_joint_setting(mesh_model, joint_category=joint_set)
  File "/content/PMCE/./main/run_demo.py", line 110, in get_joint_setting
    model = models.PMCE.get_model(num_joint=joint_num, embed_dim=256, depth=3) 
  File "/content/PMCE/main/../lib/models/PMCE.py", line 24, in get_model
    model = PMCE(num_joint, embed_dim, depth)
  File "/content/PMCE/main/../lib/models/PMCE.py", line 13, in __init__
    self.pose_mesh_coevo = CoevoDecoder.get_model(num_joint, embed_dim)
  File "/content/PMCE/main/../lib/models/CoevoDecoder.py", line 250, in get_model
    model = Pose2Mesh(num_joint, embed_dim)
  File "/content/PMCE/main/../lib/models/CoevoDecoder.py", line 200, in __init__
    init_vertices = torch.from_numpy(np.load(SMPL_MEAN_vertices)).cuda()
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/base_data/smpl_mean_vertices.npy'
```
So where can I find the 'smpl_mean_vertices.npy' ?

**Comment by kasvii** [comment]
Thanks for pointing out this. Download `base_data` from [OneDrive](https://1drv.ms/f/s!Alg46BPWJg_XgVf-q5qKdkalhgOj?e=1PZmQz). Put it below `./data` folder.

**Comment by HenrySomeCode** [comment]
> Thanks for pointing out this. Download `base_data` from [OneDrive](https://1drv.ms/f/s!Alg46BPWJg_XgVf-q5qKdkalhgOj?e=1PZmQz). Put it below `./data` folder.

Thanks! I really appreciate that. 
I met this error when re-ran the inference command again:
![image_2023_10_07T05_06_44_994Z](https://github.com/kasvii/PMCE/assets/135568083/95a3a696-868c-47eb-925b-a5c63cf7c984)
For that reason, I changed 'ModelOutput' to 'SMPLX' in smpl_mps.py follow [this](https://github.com/nkolot/SPIN/issues/89) and I met this error:
![image](https://github.com/kasvii/PMCE/assets/135568083/2a058fd6-32da-4c04-bb49-47f8f06701a1)

**Comment by kasvii** [comment]
`spin_model_checkpoint.pth.tar` has been uploaded to [OneDrive](https://1drv.ms/f/s!Alg46BPWJg_XgV0EekFWbSaQB94C?e=aEMdOI). Please download it and put it below `./data/base_data` folder.

**Comment by HenrySomeCode** [comment]
> `spin_model_checkpoint.pth.tar` has been uploaded to [OneDrive](https://1drv.ms/f/s!Alg46BPWJg_XgV0EekFWbSaQB94C?e=aEMdOI). Please download it and put it below `./data/base_data` folder.

Thanks! It's worked. After adding the `spin_model_checkpoint.pth.tar` to `./data/base_data` I have met this error 😂which said `cannot import name 'OSMesaCreateContextAttribs' from 'OpenGL.osmesa'`. I uninstalled my pyopengl with version 3.1.0 and re-installed it with version 3.1.5 and finally I got the output!
