### ISSUE TITLE
Training commands in README

### ISSUE THREAD

**Issue by zhixuanli** [kasvii/PMCE#7]
Thanks for your awesome codes!

I find that the training commands for the first and second stages are the same, leaving the `train_mesh_h36m.sh` and `train_mesh_3dpw.sh` not used. Is this correct?

---
Here's the current version of the README commands:

Stage 1 (optional): Train the 3D pose estimation stream or you can directly use our pre-traind pose model `./experiment/pretrained/pose_*.pth.tar` for Stage 2.
```bash
# Human3.6M
bash command/train_pose_h36m.sh

# 3DPW
bash command/train_pose_3dpw.sh
```

Stage 2: To train the all network for final mesh. Configs of the experiments can be found and edited in `./config` folder. Change `posenet_path` in `./config/train_mesh_*.yml` to the path of the pre-trained pose model.
```bash
# Human3.6M
bash command/train_pose_h36m.sh

# 3DPW
bash command/train_pose_3dpw.sh
```

---
# (Second question)

BTW, since there are three datasets used in the paper, could you please release the codes for the "MPI-INF-3DHP" dataset? Thanks for your brilliant work! And looking forward for your replying.

**Comment by kasvii** [comment]
You are right! The commands in stage 2 should be 'train_mesh_*.sh'. Thank you for pointing out this and I have corrected it.
We used 'MPII3D' as the short name of 'MPI-INF-3DHP' and you can find the codes [here](https://github.com/kasvii/PMCE/blob/main/data/MPII3D/dataset.py).

**Comment by zhixuanli** [comment]
Thanks for your fast reply. Now I know how to train the second stage. Thanks!

For the second question, I believe this API code in your link is very helpful. But the ".yml" files for this MPII3D dataset are missing, which makes me not know how to set the hyper-parameters or something else. Could you please add them when you have time? 

Have a good night!

**Comment by kasvii** [comment]
> Thanks for your fast reply. Now I know how to train the second stage. Thanks!
> 
> For the second question, I believe this API code in your link is very helpful. But the ".yml" files for this MPII3D dataset are missing, which makes me not know how to set the hyper-parameters or something else. Could you please add them when you have time?
> 
> Have a good night!

The training datasets for mpii3d are mixed datasets, the same as 3dpw. It can directly use the checkpoints of 3dpw to test ('bash test_mesh_mpii3d.sh'), thus there is no training script for mpii3d.

**Comment by zhixuanli** [comment]
Thank you for solving all my questions. Hopes everything is fine! :)
