### ISSUE TITLE
Using multi-gpu to accelarate

### ISSUE THREAD

**Issue by zhixuanli** [kasvii/PMCE#8]
Hi authors, 

It's me again. Happy New Year!

I'm just wondering if this copy of the codes supports using multi-GPU. I have set the GPU ids to `0,1` in the command file, which is `python ./main/train.py --cfg ./config/train_mesh_h36m.yml --gpu 0,1`. But still, only the id 0 GPU is used. 

Is there any way to use two or more GPUs to accelerate the training since at present it will take about 20 hours for the training of the second stage for the h36m dataset?

Thanks again for all your support.

**Comment by zhixuanli** [comment]
BTW, could you please tell me about the training time of your experiments on a single 3090 GPU and h36m dataset as mentioned in the paper?

On my side, this setting will cost about 30 hours in total.

**Comment by zhixuanli** [comment]
Hi, happy Friday, and have a nice weekend. 

Could you please take a look at this question when you have time? Thank you so much! :)

**Comment by kasvii** [comment]
> BTW, could you please tell me about the training time of your experiments on a single 3090 GPU and h36m dataset as mentioned in the paper?
> 
> On my side, this setting will cost about 30 hours in total.

On a single 3090 GPU, the time overheads are as follows:
mesh
● 3dpw: 30min/epoch, about half a day
● h36m: 1h25min/epoch, about a day and a half
pose
● 3dpw: 1h40min/epoch
● h36m: 25min/epoch

**Comment by kasvii** [comment]
> Hi authors,
> 
> It's me again. Happy New Year!
> 
> I'm just wondering if this copy of the codes supports using multi-GPU. I have set the GPU ids to `0,1` in the command file, which is `python ./main/train.py --cfg ./config/train_mesh_h36m.yml --gpu 0,1`. But still, only the id 0 GPU is used.
> 
> Is there any way to use two or more GPUs to accelerate the training since at present it will take about 20 hours for the training of the second stage for the h36m dataset?
> 
> Thanks again for all your support.

You could try to add 'self.model = nn.DataParallel(self.model)' in [Line1](https://github.com/kasvii/PMCE/blob/581d074c3142a22ddaf02f16ce1dc88fe94ea4e1/lib/core/base.py#L105), and [Line2](https://github.com/kasvii/PMCE/blob/581d074c3142a22ddaf02f16ce1dc88fe94ea4e1/lib/core/base.py#L200), then run the command with multi-GPUs (I have tried it and it could work).

**Comment by zhixuanli** [comment]
> > BTW, could you please tell me about the training time of your experiments on a single 3090 GPU and h36m dataset as mentioned in the paper?
> > On my side, this setting will cost about 30 hours in total.
> 
> On a single 3090 GPU, the time overheads are as follows: mesh ● 3dpw: 30min/epoch, about half a day ● h36m: 1h25min/epoch, about a day and a half pose ● 3dpw: 1h40min/epoch ● h36m: 25min/epoch

The training time of yours and mine are almost the same. Thanks for sharing.

**Comment by zhixuanli** [comment]
> > Hi authors,
> > It's me again. Happy New Year!
> > I'm just wondering if this copy of the codes supports using multi-GPU. I have set the GPU ids to `0,1` in the command file, which is `python ./main/train.py --cfg ./config/train_mesh_h36m.yml --gpu 0,1`. But still, only the id 0 GPU is used.
> > Is there any way to use two or more GPUs to accelerate the training since at present it will take about 20 hours for the training of the second stage for the h36m dataset?
> > Thanks again for all your support.
> 
> You could try to add 'self.model = nn.DataParallel(self.model)' in [Line1](https://github.com/kasvii/PMCE/blob/581d074c3142a22ddaf02f16ce1dc88fe94ea4e1/lib/core/base.py#L105), and [Line2](https://github.com/kasvii/PMCE/blob/581d074c3142a22ddaf02f16ce1dc88fe94ea4e1/lib/core/base.py#L200), then run the command with multi-GPUs (I have tried it and it could work).

This is great. Thanks!

**Comment by Dragon2938734** [comment]
> > BTW, could you please tell me about the training time of your experiments on a single 3090 GPU and h36m dataset as mentioned in the paper?
> > On my side, this setting will cost about 30 hours in total.
> 
> On a single 3090 GPU, the time overheads are as follows: mesh ● 3dpw: 30min/epoch, about half a day ● h36m: 1h25min/epoch, about a day and a half pose ● 3dpw: 1h40min/epoch ● h36m: 25min/epoch

hello, i would ask the time that "img_db = joblib.load(db_file)" in the dataset.py when load h36m，since i run the code and find it stay in this step. thank you!

**Comment by momentment** [comment]
> > > Hi authors,
> > > It's me again. Happy New Year!
> > > I'm just wondering if this copy of the codes supports using multi-GPU. I have set the GPU ids to `0,1` in the command file, which is `python ./main/train.py --cfg ./config/train_mesh_h36m.yml --gpu 0,1`. But still, only the id 0 GPU is used.
> > > Is there any way to use two or more GPUs to accelerate the training since at present it will take about 20 hours for the training of the second stage for the h36m dataset?
> > > Thanks again for all your support.
> > 
> > 
> > You could try to add 'self.model = nn.DataParallel(self.model)' in [Line1](https://github.com/kasvii/PMCE/blob/581d074c3142a22ddaf02f16ce1dc88fe94ea4e1/lib/core/base.py#L105), and [Line2](https://github.com/kasvii/PMCE/blob/581d074c3142a22ddaf02f16ce1dc88fe94ea4e1/lib/core/base.py#L200), then run the command with multi-GPUs (I have tried it and it could work).
> 
> This is great. Thanks!

hello  authors,
I try to add 'self.model = nn.DataParallel(self.model)' in [Line1](https://github.com/kasvii/PMCE/blob/581d074c3142a22ddaf02f16ce1dc88fe94ea4e1/lib/core/base.py#L105), and [Line2](https://github.com/kasvii/PMCE/blob/581d074c3142a22ddaf02f16ce1dc88fe94ea4e1/lib/core/base.py#L200),but the program still runs on GPU 0.Is there anything else that needs to be modified?
